set(_CATKIN_CURRENT_PACKAGE "diana_description")
set(diana_description_VERSION "1.0.0")
set(diana_description_MAINTAINER " <TODO@email.com>")
set(diana_description_PACKAGE_FORMAT "2")
set(diana_description_BUILD_DEPENDS )
set(diana_description_BUILD_EXPORT_DEPENDS )
set(diana_description_BUILDTOOL_DEPENDS "catkin")
set(diana_description_BUILDTOOL_EXPORT_DEPENDS )
set(diana_description_EXEC_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(diana_description_RUN_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(diana_description_TEST_DEPENDS )
set(diana_description_DOC_DEPENDS )
set(diana_description_URL_WEBSITE "")
set(diana_description_URL_BUGTRACKER "")
set(diana_description_URL_REPOSITORY "")
set(diana_description_DEPRECATED "")